### PR TITLE
Tests refactoring and cleanup

### PR DESCRIPTION
**Pull request by stokito**
Careful refacoring, nothing is broken

### CODE REVIEW

**Comment by lvca** [comment]
@stokito Thanks for the PR. Just the tests: why renaming with O as prefix? We don't use this convention or tests. Do you mind restoring their original names? And update this same PR?

**Comment by stokito** [comment]
Tests are named as class that they test

OCSVTransformer -> OCSVTransformerTest
OVertexTransformer -> OVertexTransformerTest

**Comment by stokito** [comment]
So should I rename them back?

**Comment by lvca** [comment]
Ok, makes sense.

**Comment by lvca** [comment]
Merged, thanks!

**Pull request merged**
